Support list/tuple inputs for special tokens in StartEndPacker layer
keras-team/keras-nlp pull request #1045
Opened 2023-05-16 22:41 UTC by abheesht17

2023-05-16 22:49 UTC, abheesht17 commented on keras_nlp/layers/start_end_packer.py
> +            start_value, (list, tuple)
Does this condition look good, or do we want to go with:

```
        if start_value is not None and isinstance(
            start_value, (int, str)
```

2023-05-17 04:02 UTC, mattdangerw requested changes
looks great! just minor comments

2023-05-17 04:02 UTC, mattdangerw commented on keras_nlp/layers/start_end_packer.py
>              0 or "" will be added depending on the dtype of the input tensor.
should we add an example below?

2023-05-17 17:13 UTC, mattdangerw approved these changes
Looks great!

2023-05-17 17:13 UTC, mattdangerw commented
/gcbrun

2023-05-17 18:45 UTC, merged