Add FalconBackbone
keras-team/keras-nlp pull request #1081
Opened 2023-06-15 10:43 UTC by Ruqyai

Step 2: PR #1 - Add FalconBackbone

2023-06-16 10:03 UTC, Ruqyai commented
Hi all
question about:
[class RWPreTrainedModel(PreTrainedModel):](https://huggingface.co/tiiuae/falcon-7b/blob/main/modelling_RW.py#L419-L490)  
Do you think I need to add all these details to
[keras_nlp/models/falcon/falcon_backbone.py](https://github.com/keras-team/keras-nlp/pull/1081/files#diff-dff33c35dfde4f894394e4ddba94a51618ba03f8093ebff34a4e02e720dd33ef)  ?

2023-06-16 20:19 UTC, Ruqyai commented
@mattdangerw 
Is there a solution?
If not, I'll go to the cloud ,I have credit.

![image](https://github.com/keras-team/keras-nlp/assets/13546372/24f76a9d-a704-4a03-b7ff-0e654ee8d79c)

2023-06-17 20:25 UTC, Ruqyai commented
I added the link of [Colab](https://colab.research.google.com/drive/1psl7CuukRE-NgMh9S6bOpYaSwdfP9DML?usp=sharing) in the PR . 
It is still draft.

2023-06-18 20:38 UTC, Ruqyai commented
@mattdangerw  @abheesht17

though I change the values of `hidden_size` and `num_heads` many time, I get

ValueError: `hidden_size` must be divisible by num_heads (got `hidden_size`: ( )and `num_heads`: ()).

Do you catch why is an error? [Colab](https://colab.research.google.com/drive/1psl7CuukRE-NgMh9S6bOpYaSwdfP9DML?usp=sharing)

2023-06-23 18:40 UTC, Ruqyai commented
![image](https://github.com/keras-team/keras-nlp/assets/13546372/3589be88-9c82-4f64-a153-167e0dc83666)

https://colab.research.google.com/drive/1psl7CuukRE-NgMh9S6bOpYaSwdfP9DML?usp=sharing

this is will help you to review and also I added on the colab links to each part in hugging face to compare the coding
e.g.
"""Falcon Decoder Layer
https://huggingface.co/tiiuae/falcon-7b/blob/main/modelling_RW.py#L350-L416
"""

2023-06-27 20:15 UTC, shivance commented
> I added the link of [Colab](https://colab.research.google.com/drive/1psl7CuukRE-NgMh9S6bOpYaSwdfP9DML?usp=sharing) in the PR . It is still draft.

@Ruqyai  While this works, I would recommend you to make your code compilant with our design, before opening a PR.
Please refer #1056 
Secondly, we'll be moving in RotaryEmbedding to `layers/` pretty soon, so you can remove your custom layer #1092

2023-06-27 20:22 UTC, shivance requested changes

2023-06-27 20:22 UTC, shivance commented on keras_nlp/models/falcon/falcon_mlp.py
> +class FalconMLP(keras.layers.Layer):
We can move this to decoder layer

2023-06-27 20:22 UTC, shivance commented on keras_nlp/models/falcon/falcon_rotary_positional_embedding.py
> +class FalconRotaryPositionalEmbedding(keras.layers.Layer):
#1092 is on the way !

2023-06-27 20:22 UTC, shivance commented on keras_nlp/models/falcon/falcon_attention.py
> +        self.query_key_value = Dense(
We can probably split this layer into three seperate EinsumDense layers. Can you verify?

2023-06-27 20:22 UTC, shivance commented on keras_nlp/models/falcon/falcon_attention.py
> +        if layer_past is not None:
At this stage we probably won't need this

2023-06-27 20:22 UTC, shivance commented on keras_nlp/models/falcon/falcon_backbone.py
> +        bos_token_id=1,
Again, this is not yet compilant with our design.

2023-06-29 02:52 UTC, mattdangerw commented
This would probably need some reworks from the source code to match the model style we use in this repo.

- Always take in named parameters to init, not `config` objects.
- Make sure argument names are self consistent, and consistent across the library. `num_layers` not `n_layers`, etc. Our [style guide](https://github.com/keras-team/keras-nlp/blob/master/STYLE_GUIDE.md) the [keras API guide](https://github.com/keras-team/governance/blob/master/keras_api_design_guidelines.md) cover some of this.
- Try to align the flow of our calls as much with `TransformerDecoder` and `MultiHeadAttention` as possible. Totally acceptable to have a separate transformer block, but we should try to match the general flow, and arguments as much as possible.

We should also make sure to try to support a fairly minimal set of configuration options. E.g. I see options for RoPE and ALiBi here, but if our checkpoints only need one of these, we should only support what we need. Better to be minimal than exhaustive here, especially for review!

2023-07-04 11:01 UTC, Ruqyai commented
> This would probably need some reworks from the source code to match the model style we use in this repo.
> 
> * Always take in named parameters to init, not `config` objects.
> * Make sure argument names are self consistent, and consistent across the library. `num_layers` not `n_layers`, etc. Our [style guide](https://github.com/keras-team/keras-nlp/blob/master/STYLE_GUIDE.md) the [keras API guide](https://github.com/keras-team/governance/blob/master/keras_api_design_guidelines.md) cover some of this.
> * Try to align the flow of our calls as much with `TransformerDecoder` and `MultiHeadAttention` as possible. Totally acceptable to have a separate transformer block, but we should try to match the general flow, and arguments as much as possible.
> 
> We should also make sure to try to support a fairly minimal set of configuration options. E.g. I see options for RoPE and ALiBi here, but if our checkpoints only need one of these, we should only support what we need. Better to be minimal than exhaustive here, especially for review!

Thanks, I fixed the __init__ parameters, but I still have an error in the attention module. It's about the dimensions and shapes of the tensors involved in the reshape operation. 
@shivance @mattdangerw can you help in this point?

2023-07-07 18:58 UTC, Ruqyai commented
Good News
These I watched these links and fixed a lot of errors :)
https://youtu.be/yJgSGE2-L_o
https://youtu.be/8IMei5V-2ok
https://youtu.be/GVShIIh3_yE

2023-07-26 06:15 UTC, shivance requested changes

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_decoder.py
> +    Inputs:
Please add examples or we could just drop it for now.

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_decoder.py
> +    Args:
We don't use config.

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_decoder.py
> +        config.update(
Please add rest of attributes here.

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_mlp.py
> +class FalconMLP(keras.layers.Layer):
@Ruqyai update on this?
I recommend you to go through other transformers. We don't create a seperate MLP class.

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_rotary_positional_embedding.py
> +    Input Shape:
The docstring format is incorrect.

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_rotary_positional_embedding_test.py
Could you delete this empty file ?

2023-07-26 06:15 UTC, shivance commented on keras_nlp/models/falcon/falcon_attention.py
> +    def call(self, hidden_states, attention_mask=None, alibi=None, layer_past=None, head_mask=None,
Please run `black` to format code.

2023-07-26 06:16 UTC, shivance commented
The rule of thumb while contributing a model is to open PR for backbone first, once that gets in, one should proceed for preprocessors, tasks etc.

2023-07-26 06:20 UTC, shivance commented
Additionally, we should migrate this PR to use Keras Core instead of tf.keras

2023-12-04 19:24 UTC, closed without merging