Add Whisper Speech-to-Text
keras-team/keras-nlp pull request #1114
Opened 2023-07-05 22:47 UTC by abheesht17

2023-07-11 23:21 UTC, mattdangerw requested changes
I think there are still some correctness issue we are debugging. But left some general code comments in meantime.

2023-07-11 23:21 UTC, mattdangerw commented on keras_nlp/models/whisper/whisper_audio_to_speech_lm.py
> +class WhisperAudioToSpeechLM(GenerativeTask):
I think we should still probably call this seq2seq for consistency, after all, we didn't call it `BartTextToTextLM`.

2023-07-11 23:21 UTC, mattdangerw commented on keras_nlp/models/whisper/whisper_audio_to_speech_lm.py
> +    """
Given that we have presets, we can probably go ahead and add docstrings. Also keep in mind that after the multi-backend changes, we will favor `np.array` over `tf.constant`.

2023-07-11 23:21 UTC, mattdangerw commented on keras_nlp/models/whisper/whisper_audio_to_speech_lm_preprocessor.py
> +    This layer is used as preprocessor for seq2seq tasks using the Whisper model.
maybe use this language instead https://github.com/keras-team/keras-nlp/blob/03668b87b6aae0e4d87cda041e07e2dc81736331/keras_nlp/models/gpt2/gpt2_causal_lm_preprocessor.py#L33-L43

a little more up to date

2023-07-11 23:21 UTC, mattdangerw commented on keras_nlp/models/whisper/whisper_tokenizer.py
> +        self.end_token_id = self.eos_token_id
This is kind of an awkward line. Can we just update the whole layer to use `end_token_id` and `start_token_id`? That will be more consistent with the rest of the library.

2023-10-25 11:41 UTC, abheesht17 commented
Closing this, will open a new PR.

2023-10-25 11:41 UTC, closed without merging