Whitelisted formatting and lint check targets
keras-team/keras-nlp pull request #126
Opened 2022-04-16 09:21 UTC by adhadse

Resolves #104.

The proposed solution intends to whitelist directories/files that are supposed to be formatted and lint checked.
From current scenario it looks that the bash scripts don't perform really well with PowerShell, so WSL is recommended for project development on Windows platform.

Other than that, `lint.sh` continues to fail with error "Broken 1 Paths" while the input argument are same as in `format.sh`. This is discussed in above  issue.

- [X] `format.sh` fixed
- [ ] `lint.sh` fixed

2022-04-18 20:12 UTC, mattdangerw requested changes
Looks good! Few comments.

2022-04-18 20:12 UTC, mattdangerw commented on shell/format.sh
> +for i in $(find ${target_dir} -name '*.py'); do
Can you just you targets here? Prefer to avoid the duplicated variable above.

2022-04-18 20:12 UTC, mattdangerw commented on shell/lint.sh
> +for i in $(find "${target_dir}" -name '*.py'); do
Same here, use targets, remove other variable.

2022-04-19 14:13 UTC, adhadse commented
Ready to Merge!!!

2022-04-21 00:52 UTC, mattdangerw approved these changes
Thanks! This looks good, approving. I will test out and merge shortly.

2022-04-21 19:57 UTC, merged