top p search and testing
keras-team/keras-nlp pull request #233
Opened 2022-06-24 22:30 UTC by jessechancy

2022-06-25 00:01 UTC, chenmoneygithub requested changes
Thanks! Mainly looks good, left some comments

2022-06-25 01:11 UTC, jessechancy commented on keras_nlp/utils/text_generation.py
> +            shifted_keep_mask, sorted_preds, tf.fill(pred.shape, filter_value)
Yep filter_value should be 0, edited

2022-06-25 01:12 UTC, jessechancy commented on keras_nlp/utils/text_generation.py
> +        filter_value: float, defaults to -Inf. The value for filtering out
I don't think we need to allow customization, we can just mask out tokens that are unused by having filter_value = 0

2022-06-25 01:12 UTC, jessechancy commented on keras_nlp/utils/text_generation.py
> +            pred, k=pred.shape[-1], sorted=True
edited

2022-06-25 01:12 UTC, jessechancy commented on keras_nlp/utils/text_generation_test.py
> +class TopPSamplingTextGenerationTest(tf.test.TestCase):
edited for this and other testing names

2022-06-27 18:25 UTC, chenmoneygithub requested changes
only a few minor comments!

2022-06-27 18:25 UTC, chenmoneygithub commented on keras_nlp/utils/text_generation.py
> +        filter_value: float, defaults to -Inf. The value for filtering out
Yea, in that case, let's remove this argument.

2022-06-27 18:25 UTC, chenmoneygithub commented on keras_nlp/utils/text_generation_test.py
> +        # Test that it only samples from tokens that sum up to p
nit: period at end.

2022-06-27 19:36 UTC, chenmoneygithub approved these changes

2022-06-28 00:19 UTC, mattdangerw approved these changes
This looks great! Nice work.

Just a few minor comments

2022-06-28 00:19 UTC, mattdangerw commented on keras_nlp/utils/text_generation.py
> +    Top-p search filters the top token with probabilities that sum up to p, and
maybe we can explain this a little more clearly, also remember to backtick argument names so it's clear what they are...

Top-p search selects tokens from the smallest subset of output probabilities that sum to greater than `p`. Put another way, top-p will first order token predictions by likelihood, and ignore all tokens after the cumulative probably of selected tokens exceeds `p`.

2022-06-28 00:35 UTC, mattdangerw commented on keras_nlp/utils/text_generation.py
> -    # Print the generated sequence (token ids).
typo?

2022-06-28 00:44 UTC, mattdangerw commented on keras_nlp/utils/text_generation.py
> -    # Print the generated sequence (token ids).
fixed

2022-06-28 00:53 UTC, merged