Add Checkpoint Conversion Notebook for `bert_base_chinese`
keras-team/keras-nlp pull request #319
Opened 2022-08-27 13:44 UTC by abheesht17

Comments:

- The [TF Model Garden checkpoint](https://storage.googleapis.com/tf_model_garden/nlp/bert/v3/chinese_L-12_H-768_A-12.tar.gz) for `bert_base_chinese` does NOT have weights for the pooled output layer. So, I have skipped that layer and compared `sequence_outputs` of the TF model and our loaded model.
- We use WordPiece tokenizer here, and it works fine because CJK characters are included in `PUNCTUATION_REGEX`. Please see [this comment](https://github.com/keras-team/keras-nlp/pull/318#issue-1352962625) for more details.

Converted model weights and vocab have been uploaded here: https://drive.google.com/drive/folders/19APUi7fobORdQjoe8YDyk8ou0x_L6hWu?usp=sharing.

2022-08-29 18:43 UTC, mattdangerw commented
@abheesht17 I think we would want to avoid the add_pooling_layer parameter if possible.

One thing we could check is the bert checkpoints on the original bert repo. Could you see if those include the pooling layer?

https://github.com/google-research/bert

2022-08-30 15:18 UTC, abheesht17 commented
> @abheesht17 I think we would want to avoid the add_pooling_layer parameter if possible.
> 
> One thing we could check is the bert checkpoints on the original bert repo. Could you see if those include the pooling layer?
> 
> https://github.com/google-research/bert

My bad. The pooling layers are present in this ckpt after all: https://storage.googleapis.com/tf_model_garden/nlp/bert/v3/multi_cased_L-12_H-768_A-12.tar.gz. Missed them earlier

2022-09-01 02:27 UTC, mattdangerw requested changes
This looks good! We recently renamed the inputs to the models, could you make the changes in your colab to match?
https://github.com/keras-team/keras-nlp/pull/327

I think we are fine with the weights we have now (as the variable names do not depend on the input names), but might be good to double check the rename did not break the weights we uploaded.

2022-09-01 02:27 UTC, mattdangerw commented on tools/checkpoint_conversion/bert_base_multi_cased.ipynb
> +        "    weights[f\"encoder/layer_with_weights-{i + 5}/kernel/.ATTRIBUTES/VARIABLE_VALUE\"]\n",
This is using a variable (i) that is not out of scope. Can't you just do num_layers + X?

Same comment for other colab.

2022-09-01 05:41 UTC, abheesht17 commented
> This looks good! We recently renamed the inputs to the models, could you make the changes in your colab to match? #327
> 
> I think we are fine with the weights we have now (as the variable names do not depend on the input names), but might be good to double check the rename did not break the weights we uploaded.

I think I already changed the names yesterday.

2022-09-01 19:44 UTC, merged