Create `Backbone` base class
keras-team/keras-nlp pull request #621
Opened 2022-12-28 23:51 UTC by jbischof

Prototype of how base classes could improve the maintainability of our library. The `Backbone` class can be easily extended to other model types and `Task`, `Preprocessor`, and `Tokenizer` base classes can also be added.

I've also simplified the `from_preset` docstring so we don't have to write a lot of custom copy for each model class. We already have all the information we need in the class docstring.

Part of #530

2023-01-03 20:22 UTC, mattdangerw requested changes
Thanks! This will be a nice change. Left some comments.

2023-01-03 20:22 UTC, mattdangerw commented on keras_nlp/models/base.py
> +        """Instantiate {model_name} model from preset architecture and weights.
I would just do the class name everywhere in this format string. Keeps things simpler and more automated. And when we refer to the model we have done that stylized as `BERT` right? So probably better to stick to `BertBackbone` here.

2023-01-04 22:49 UTC, jbischof commented on keras_nlp/models/base.py
> +        model = {model_name}Backbone.from_preset({example_preset_name})
I get this error: 
```
AttributeError: attribute '__doc__' of 'method' objects is not writable
```

I wonder why it works as a decorator and not posthoc...

2023-01-04 22:58 UTC, jbischof commented on keras_nlp/models/base.py
> +        model = {model_name}Backbone.from_preset({example_preset_name})
Here's what seems to work:
```python
format_docstring(
    model_name=BertBackbone.__name__,
    example_preset_name="bert_base_en_uncased",
    preset_names=BertBackbone.presets,
)(BertBackbone.from_preset.__func__)
```

2023-01-04 23:25 UTC, mattdangerw commented on keras_nlp/models/base.py
> +        model = {model_name}Backbone.from_preset({example_preset_name})
kinda funky, but I'm down to do this for now! and at least our "formattable docstring" style is consistent

we can always update if we find a better recipe

2023-01-04 23:26 UTC, mattdangerw approved these changes
LGTM! Thanks!

2023-01-04 23:39 UTC, mattdangerw commented on keras_nlp/models/backbone.py
> +        model = {{model_name}}Backbone.from_preset({{example_preset_name}})
Oops missed a spot, this should be `{{model_name}}.from_preset` (remove the Backbone)

2023-01-04 23:39 UTC, mattdangerw commented on keras_nlp/models/backbone.py
> +        model = {{model_name}}Backbone.from_preset(
Same here

2023-01-05 00:53 UTC, mattdangerw approved these changes

2023-01-05 01:15 UTC, merged