Add Fence Docstring Testing
keras-team/keras-nlp pull request #640
Opened 2023-01-06 11:46 UTC by abheesht17

2023-01-10 03:09 UTC, mattdangerw requested changes
Awesome! This is super super useful for the library. Left some questions.

2023-01-10 03:09 UTC, mattdangerw commented on keras_nlp/tests/doc_tests/fenced_docstring_lib.py
> +    2. We need the last expression to be printed (harder).
I wonder if we want this... Nothing relies on output after a fenced code block today, but we could add this in.

Will discuss with folks.

2023-01-10 03:43 UTC, mattdangerw commented
@abheesht17 also it looks like things are failing on ci because of the lack of `astor`. We should add that (and any other new pip dependencies) to `requirements-common.txt`.

2023-01-13 19:26 UTC, abheesht17 commented
@chenmoneygithub, could you pleas generate a docker image for this? I've added `astor` to `requirements_common.txt`. Thanks!

2023-01-13 22:20 UTC, mattdangerw commented on keras_nlp/models/backbone.py
> +        doctest.skip
Let's remember to remove this.

2023-01-17 19:32 UTC, mattdangerw commented on keras_nlp/tests/doc_tests/docstring_test.py
> +    "`test_fenced_docstrings` requires `astor`. Please run `pip install astor`."
We don't usually keep warning string in constant like this, I'm just going to inline this.

2023-01-17 19:34 UTC, mattdangerw approved these changes
Thanks! LGTM!

2023-01-17 19:57 UTC, merged