Add FNet Presets
keras-team/keras-nlp pull request #659
Opened 2023-01-14 08:52 UTC by abheesht17

2023-01-15 19:38 UTC, jbischof requested changes
Looks great, just some nits!

2023-01-15 19:38 UTC, jbischof commented on keras_nlp/models/deberta_v3/deberta_v3_presets.py
> +            "Large size of DeBERTaV3. "
Move to separate PR.

2023-01-15 19:38 UTC, jbischof commented on keras_nlp/models/f_net/f_net_tokenizer.py
> +        """Instantiate anDeBERTa tokenizer from preset vocabulary.
Update docstring

2023-01-15 19:38 UTC, jbischof commented on keras_nlp/models/f_net/f_net_tokenizer.py
> +        tokenizer = keras_nlp.models.DebertaV3Tokenizer.from_preset(
Update docstring

2023-01-18 03:11 UTC, mattdangerw commented on keras_nlp/models/f_net/f_net_preprocessor.py
> +FNetPreprocessor.from_preset.__func__.__doc__ = Preprocessor.from_preset.__doc__
this can be removed now, and the from_preset redefinition

2023-01-18 21:07 UTC, mattdangerw approved these changes
Thank you!

2023-01-18 21:07 UTC, merged

2023-01-18 22:54 UTC, jbischof reviewed
Thanks!