Add a DistilBertMaskedLM task model
keras-team/keras-nlp pull request #724
Opened 2023-02-05 14:39 UTC by ADITYADAS1999

*   Add a `DistilBertMaskedLMPreprocessor` preprocessor layer and tests.
 *   Add a `DistilBertMaskedLM` task model and tests.

2023-02-07 23:51 UTC, mattdangerw requested changes
Thank you! Left some initial comments, also looks like there are some test failures that need investigation.

2023-02-07 23:51 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_masked_lm_preprocessor.py
> +    `keras_nlp.models.DistilBertMaskedLM` task model. Preprocessing will occur in
fix line length

2023-02-07 23:51 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_masked_lm_preprocessor.py
> +        mask_token_rate: float, defaults to 0.8. `mask_token_rate` must be
This is prexising I know, but let's remove these defaults for this arg and below (we don't do this for other args in this list)

2023-02-07 23:51 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_masked_lm_preprocessor.py
> +    - Pack the inputs together with the appropriate `"<s>"`, `"</s>"` and
These are not the special tokens used by DistilBert, this will need updating.

2023-02-07 23:51 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_masked_lm_preprocessor.py
> +    vocab = {"<s>": 0, "<pad>": 1, "</s>": 2, "<mask>": 3}
this is not the right format for the vocabulary for this model, will need updating.

2023-02-07 23:51 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_masked_lm.py
> +    [here](https://github.com/facebookresearch/fairseq).
update this to the right disclaimer for the model, distilbert is huggingface

2023-02-08 03:14 UTC, ADITYADAS1999 commented
> Thank you! Left some initial comments, also looks like there are some test failures that need investigation.

thanks @mattdangerw for review, 
I run test locally and get some test failure 

![test_summary](https://user-images.githubusercontent.com/58718316/217419522-c0314849-f150-4e01-b718-c027ab13bf77.PNG)

2023-02-08 04:43 UTC, ADITYADAS1999 commented
> > Thank you! Left some initial comments, also looks like there are some test failures that need investigation.
> 
> thanks @mattdangerw for review, I make all the changes and run test locally. 

![test_summary](https://user-images.githubusercontent.com/58718316/217435504-ad8ee0e0-6e80-4e0f-8840-bf0874864699.PNG)

2023-02-09 19:19 UTC, mattdangerw commented
@ADITYADAS1999 thanks! Look like there are still some test failure to fix in the preprocessor layer you are adding from your screen shot! You can also see the failures in the automatic testing running on this PR.

2023-02-10 02:52 UTC, ADITYADAS1999 commented
> @ADITYADAS1999 thanks! Look like there are still some test failure to fix in the preprocessor layer you are adding from your screen shot! You can also see the failures in the automatic testing running on this PR.

yes , I working on this....

2023-02-12 14:12 UTC, ADITYADAS1999 commented
hey @mattdangerw all the tests are checked , can you review for necessary changes.

2023-02-20 19:02 UTC, shivance commented
@mattdangerw I just left some comments, as peer review. I hope peer review is allowed at KerasNLP ! I would request you to take a look as well Before @ADITYADAS1999 addresses them.

2023-02-21 02:50 UTC, ADITYADAS1999 commented
> @mattdangerw I just left some comments, as peer review. I hope peer review is allowed at KerasNLP ! I would request you to take a look as well Before @ADITYADAS1999 addresses them.

hey @shivance is there a issue in PR ? can you explain little bit.

2023-02-23 01:37 UTC, mattdangerw commented
@shivance you are welcome to leave comments if you spot things, but I don't actually see anything. Did you mean to post something to this PR?

2023-02-23 01:44 UTC, shivance commented
@ADITYADAS1999 @mattdangerw Could you check now, if my comments are visible?

2023-02-23 03:08 UTC, ADITYADAS1999 commented
> @ADITYADAS1999 @mattdangerw Could you check now, if my comments are visible? ![image](https://user-images.githubusercontent.com/51750587/220803642-f6d61355-f129-4183-b722-758d148a839f.png)

yes @shivance  it's visible for me. 

@mattdangerw is it visible for you ?

2023-02-23 04:11 UTC, mattdangerw commented
Yes all visible now! With github I often "Start a review" but forgot to finish, if you don't finish the review your comments will not post.

2023-02-23 04:19 UTC, shivance commented
> Yes all visible now! With github I often "Start a review" but forgot to finish, if you don't finish the review your comments will not post.

Yes Yes, That's what happened 😅. Reviewed a PR for the first time.

2023-02-23 04:39 UTC, mattdangerw approved these changes
Thank you! This looks good!

There is one comment re the saved model test from @shivance that is worth doing. 

I'm running a quick training job to make sure things look ok, can merge when that is done.

2023-02-23 04:39 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_tokenizer.py
> +        mask_token = "[MASK]"
Looks like that is already done on the line below. So I think we are all set here.

2023-02-24 01:32 UTC, mattdangerw commented
Thanks pulling this in now! Here's the trial run -> https://gist.github.com/mattdangerw/b16c257973762a0b4ab9a34f6a932cc1

2023-02-24 03:01 UTC, merged

2023-02-24 03:09 UTC, ADITYADAS1999 commented
Thank you @mattdangerw 🎉

2023-02-24 17:06 UTC, ADITYADAS1999 commented
Hey @mattdangerw I want to participate gsoc this year, can you guide or advice in project idea, proposals docs in kerasNLP ? 👨‍💻