bert_tiny_uncased_en_sst2 added
keras-team/keras-nlp pull request #771
Opened 2023-02-23 07:33 UTC by susnato

### What does this PR do?
As discussed in this [issue](https://github.com/keras-team/keras-nlp/issues/542), this PR updates the previous [training script](https://github.com/keras-team/keras-nlp/blob/master/tools/checkpoint_training/bert_tiny_uncased_en_sst2_training.ipynb) for finetuning BERT on SST2. 

The colab link is this : https://colab.research.google.com/drive/1afTO0ahF3vZrJtkVSGXwBLV2OGeDfomL?usp=sharing

Valdiation Scores achieved : 
```
Epoch 1/2
4210/4210 [==============================] - 828s 191ms/step - loss: 0.3782 - sparse_categorical_accuracy: 0.8299 - val_loss: 0.4344 - val_sparse_categorical_accuracy: 0.8165
Epoch 2/2
4210/4210 [==============================] - 783s 186ms/step - loss: 0.2409 - sparse_categorical_accuracy: 0.9039 - val_loss: 0.4626 - val_sparse_categorical_accuracy: 0.8222
```

@chenmoneygithub

2023-02-23 07:38 UTC, susnato commented
I signed the form so `cla/google` and it's green now.

2023-02-26 02:18 UTC, susnato commented
Hi @chenmoneygithub I finetuned `BertClassifier` again on `SST2` as you said. Please check it.

2023-02-28 03:30 UTC, chenmoneygithub commented
@susnato Thanks a lot! Looks beautiful overall!

Another thing you may want to do is to use a decayed learning rate:
```
lr = tf.keras.optimizers.schedules.PolynomialDecay(
    5e-5,
    decay_steps={total_training_steps},
    end_learning_rate=0.0,
)
```

Please let me know how it works, thx again!

2023-02-28 22:43 UTC, mattdangerw commented
Just a drive by comment, but we should replace, not copy, the old colab with this PR. We don't want to keep spawning versions of the colab each time we update something.

2023-03-06 03:03 UTC, chenmoneygithub commented
@susnato Hi! sorry for the late reply, I was on vacation the last week. This is a bit odd to me, in my experiments the decayed lr generally works better (but I tried it with BERT base model). If this is stable on your side, it sounds good to stay with the constant `lr`.

2023-03-06 03:23 UTC, chenmoneygithub requested changes

2023-03-06 03:23 UTC, chenmoneygithub commented on tools/checkpoint_training/bert_tiny_uncased_en_sst2_training.ipynb
> +}
nit: newline at the end

2023-03-06 03:23 UTC, chenmoneygithub commented on tools/checkpoint_training/bert_tiny_uncased_en_sst2_training.ipynb
> +      "cell_type": "code",
nit: delete the empty cell

2023-03-06 04:55 UTC, susnato commented
Hi @chenmoneygithub thanks a lot for your comments! I made the changes you requested, please check them.

2023-03-06 04:56 UTC, chenmoneygithub approved these changes

2023-03-07 04:37 UTC, chenmoneygithub commented
@susnato Oh one more thing - could you run ./shell/format.sh in your branch? the style check is broken.

2023-03-07 05:30 UTC, susnato commented
@chenmoneygithub Done!

2023-03-08 07:33 UTC, susnato commented
Hi @chenmoneygithub the `Check the code format` is passed! but there seems to be an error with `
keras-nlp-accelerator-testing` is this something related to my code?

2023-03-10 01:06 UTC, chenmoneygithub commented
@susnato That one is okay, don't worry.

2023-03-10 01:06 UTC, merged