Speeding the tests for whisper
keras-team/keras-nlp pull request #887
Opened 2023-03-20 08:34 UTC by susnato

What does this PR do?
This PR modifies tests as described in https://github.com/keras-team/keras-nlp/issues/866 for `whisper`.

**Results**
before - 9 passed, 3 skipped in 22.53s
after - 8 passed, 4 skipped in 7.96s

@mattdangerw @chenmoneygithub

2023-03-21 03:03 UTC, mattdangerw requested changes
Looks good! Just one comment

2023-03-21 03:03 UTC, mattdangerw commented on keras_nlp/models/whisper/whisper_backbone_test.py
>                  vocabulary_size=1000,
let's size down this backbone same as above.

2023-03-21 13:43 UTC, susnato commented
Hi @mattdangerw I made those changes that you requested. Please check

2023-03-22 03:56 UTC, mattdangerw commented
LGTM!

2023-03-22 03:56 UTC, mattdangerw approved these changes

2023-03-22 03:56 UTC, merged