Remove the old sampler utilities
keras-team/keras-nlp pull request #948
Opened 2023-03-31 02:11 UTC by mattdangerw

The code developed here all lives on in the new sampler API!

2023-04-03 18:50 UTC, chenmoneygithub requested changes
Thanks!

2023-04-03 18:50 UTC, chenmoneygithub commented on benchmarks/text_generation.py
>  from tensorflow import keras
We need to update this README with new metrics: https://github.com/keras-team/keras-nlp/blob/master/benchmarks/README.md

2023-04-03 18:55 UTC, jbischof commented
Love the work thank you!

2023-04-04 05:01 UTC, chenmoneygithub approved these changes

2023-04-04 05:01 UTC, chenmoneygithub commented on benchmarks/README.md
> +On running this script on Google Colab (with 3090 GPU, and TensorFlow 2.11.0),
I should probably upgrade my PC 🛩️

2023-04-04 15:22 UTC, abheesht17 commented
Minor comment, but this change will break this example (after release): https://keras.io/examples/nlp/neural_machine_translation_with_keras_nlp/. Considering this example is kinda popular, we should open a "contributions welcome" issue for this.

2023-04-04 15:33 UTC, abheesht17 commented on benchmarks/README.md
> +|      Top-p Search     	|        401.97        	|             260.31             	|
Damn, crazy speedup!

2023-04-04 17:01 UTC, mattdangerw commented
> Minor comment, but this change will break this example (after release): https://keras.io/examples/nlp/neural_machine_translation_with_keras_nlp/. Considering this example is kinda popular, we should open a "contributions welcome" issue for this.

Yeah absolutely. Was going to file a contributor issue to do this as https://github.com/keras-team/keras-nlp/pull/896 lands. Doesn't make too much sense to do while we are still tweaking the sampler interface.

2023-04-04 17:01 UTC, mattdangerw commented
/gcbrun

2023-04-04 18:35 UTC, mattdangerw commented
/gcbrun

2023-04-04 20:19 UTC, merged