Mark  as required in Classifier classes
keras-team/keras-nlp pull request #971
Opened 2023-04-07 00:59 UTC by chenmoneygithub

resolve #955

2023-04-07 01:02 UTC, chenmoneygithub commented
/gcbrun

2023-04-07 23:22 UTC, mattdangerw commented
There are some legit failures in our `"large"` testing, take a look!

2023-04-07 23:27 UTC, mattdangerw requested changes
Looks good overall! One major comment and some test failures.

2023-04-07 23:27 UTC, mattdangerw commented on keras_nlp/models/distil_bert/distil_bert_classifier.py
> +        num_classes,
I think if we just follow @jbischof's work in CV here, we should not extend `from_preset` everywhere, and just rely on the fact we will get a somewhat descriptive error if `num_classes` is not provider via kwargs.

There is probably some work we could do with a try/catch block on the base `Task` class to improve the error message if we would like, but I don't think we want to redefine `from_preset` everywhere. The goal should be keeping the end task classes, as short and concise as we can!

2023-04-08 01:11 UTC, chenmoneygithub commented
/gcbrun

2023-04-10 18:42 UTC, chenmoneygithub commented
/gcbrun

2023-04-12 00:07 UTC, chenmoneygithub commented
/gcbrun

2023-04-12 00:07 UTC, chenmoneygithub commented on keras_nlp/models/albert/albert_presets_test.py
> +                    num_classes=2,
good idea, done

2023-04-12 01:02 UTC, chenmoneygithub commented
/gcbrun

2023-04-12 06:32 UTC, merged